### ISSUE TITLE
0.9.19 Koala Checklist

### ISSUE THREAD

**Issue by mlynch** [ionic-team/ionic-site#96]
- [ ] Update slidebox docs to reflect new SlideBoxDelegate
- [ ] Explain new nav system
- [ ] Explain new ScrollDelegate
- [ ] talk about how to set the active index and the new features for the slidebox
- [ ]
